apiVersion: v1
kind: Secret
metadata:
  name: questify-secret
stringData:
  postgres-password: ENC[AES256_GCM,data:BcMXcQexRbGt1UqAeKesfIzRjLXq1y2g,iv:oRFLGdUoF7VWfpWzCv2qeC5jVmzmNUOsncnsYrXCDmk=,tag:mjTAF78XX2ywj0AYu/21Rw==,type:str]
  rabbitmq-password: ENC[AES256_GCM,data:ruaObJ/vt8WPb3I74f1tUfZYqHeKHg2G,iv:A2Sl2ju0ViRB5naGUT8xPMR9z6QR5uYWz2pFgk3aLjQ=,tag:Rlf9ZjCCk3iGP5ehHa26Qg==,type:str]
  jwt-secret: ENC[AES256_GCM,data:VoJwfSil+jy4aCoDjsfTL/bGyRUQGOAuy9tbY7jbdJwhZGQ4z4fhWtHQhj7+xwWwwClB9/iVjsiLmMGe+C4+Og==,iv:nBEBhXrwoGa/1/rbLKC02/caqUdLtw/GJmgwQhjznJc=,tag:o/WMv5vOQe1jVISNWXesfw==,type:str]
  garage-rpc-secret: ENC[AES256_GCM,data:v1DCAAtrUk6sKPAILh3qNSD3IM3pMNoH7CL2lhfeOskWfuaaXoAY7No9hpJpSJquoXbpYSYVkLJHjBhiFXIDcg==,iv:AI+B2/Qpx7UUFNlRQa4GADrkpVaDgPTTmsR+n380mLw=,tag:C/ogYF52+/MdxvKhrPxO+w==,type:str]
  garage-access-key-id: ENC[AES256_GCM,data:8m+dieRMVGCZaoD8EKAQOvS5SJY9ADaa4WI=,iv:yOwabrSeTMgWLTj60c08SRZHbsUuSn0Ir3b9xuTu/1s=,tag:IMbRVagv7IQ4jRCpwY2iXA==,type:str]
  garage-secret-access-key: ENC[AES256_GCM,data:08nvUTaxMd+JwYBvRZyc2t0TPUqqrexzY0OpVOD21Dzn6OmuXzYfQS+WUXpzNidS/iGEFn+M0BvW1dvvBmoIDw==,iv:H+SYflyxk6gRuhtNHs5mn++S62a2SOBOg3kxIC7Q46Y=,tag:0iE4kyI3utar3imz1LJQaQ==,type:str]
  quest-db-password: ENC[AES256_GCM,data:6NEkUzJeqVuKbjzhNMEXxmQ8ZdLzhF1p,iv:Qej4PZSsrzQ4T2YES+V1D+3Aq8hqPXbEQXUTs6JS/+M=,tag:WVMHU+F2K/Jn1+DG62TsPQ==,type:str]
  project-db-password: ENC[AES256_GCM,data:iM6+VPRFVU/jw2SGAwgucL2mFtenhJvf,iv:xFA0rfbode93jTN4qli3DCE2bXQZ4fZjngAkSfwbcLs=,tag:bqLPOZg0VCQxWrpvKw35EA==,type:str]
  progression-db-password: ENC[AES256_GCM,data:fd3/DVjBqSjnfr7IrNVXPh2DLwlkqrDh,iv:09Sder/Ar/U2x/dalAR1L8CAB5V2fGuHtO0dMpcY1J0=,tag:qD4nYHYib6dP283DIdMjhw==,type:str]
  stats-db-password: ENC[AES256_GCM,data:qUoZrmhRYbORnzMpslYob2l5jvBO43Y3,iv:KAs+cZqLAuXgJJH7EVoBQ2VCa90DVQh+P7a5KxKP93I=,tag:GTGw/DuIhyubu9y0iHGPvg==,type:str]
  admin-db-password: ENC[AES256_GCM,data:WMka2ElWGVgq6hmwZQ5cVZoCfoxDMe0w,iv:a3mPDs0e3tkExoKhbIpIGd7OHIAyXQuO6YuZIVD0k5w=,tag:jg6qQpL3k1EYL/non14vnA==,type:str]
  admin-bootstrap-password: ENC[AES256_GCM,data:oY+mz0USR6WqkjoiZrBk8w+bmvBBVn85,iv:MiNIIQ+Ku4XS6ERFX5yutNY1d33IgmqQqa196Aw+QTc=,tag:Fe6SIWAlvgOxzy4R2Iag0Q==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZzM1OFhWK05iMDRVVGpT
        VGpSZno5VWFUWC9OcUdWSkJQZ29JckRnd0dVCmYwQ1l4bzZtakJWYThBUldDeW5C
        UGRCb2d1cGZubWhqVjh5WU1PcWE0MG8KLS0tIDFodTVqSXZNWkFUZXc1MlB5UFUr
        WkozQW9QbWJObHhsdndJdVNFK0d3U1EK/Ct5GFSkSQwAQYBIgE/SUzcIM1Sz/Q0V
        8ytJR3W8z4cOT/cwkkxmDjsqaBCzaiBdcXf4El2VZj5+xUTorn3ukw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T20:36:33Z"
  mac: ENC[AES256_GCM,data:0+t5bwE5w5hbFWLdLfnzRHAXnlrSremP+Vi1rhVr/6D5ffmcA+8wRwLj6IWSdjz6dpnFv9xbWws621vsCzIGTHGrVuJxBnmVO5bzHxvRxCQyvxMHdyrkddq6VQk/JLdBMYLtD/G2CSZGkFGLx3KaqFDtO8/5bAhyMHHKDMkzOQY=,iv:D/mn/rZDH9e8pOSqMGrfH2IeqS8qbLxiqYRv88uzRSg=,tag:Yt4mHPAX4a14+F7DVBUQcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
