apiVersion: v1
kind: Secret
metadata:
  name: questify-secret
stringData:
  keycloak-service-account-secret: ENC[AES256_GCM,data:c66KHAh3JLjqJ0x17JLNtDkoGgCCvjHN89tAqK47fQY=,iv:zQcNrOHPFJ+KUcepn83JDhdrOT9ow3po3SNCOsvCQ0k=,tag:6shvedGED8cQzLQHTvydlA==,type:str]
  admin-bootstrap-password: ENC[AES256_GCM,data:fMpJ9xDfB34InQco9NuBKXq7za9x6OGA,iv:4sRqEdUWaEfe80jztuNxURe3i5yFb1MkH+j5iyCGEsE=,tag:uHyTb8gV+DWD07BmPT/oDQ==,type:str]
  admin-db-password: ENC[AES256_GCM,data:iSSMBe154swAKj25TJWfhAdGRYwbaXd1,iv:IuqoJ4KHWZK8kGcVb21/V3ExNKNYef0Fnb53sr01pkU=,tag:6eIl2nyM4+ZpuyC7+IiNbA==,type:str]
  admin-email: ENC[AES256_GCM,data:Mzpln60W6xujtCoPZkWpOHm0C8w=,iv:c6Hr+cHWGKqMkFGkUB72niA8HnLsuXLnr3m21dGMDiU=,tag:kBZRhEz3yIsG+COefLqgqQ==,type:str]
  garage-access-key-id: ENC[AES256_GCM,data:EXSX3JX0Q4q2hG9pxPHOz9LPRZlhMNKSMPY=,iv:UQL5NFV5IKGsySBZRPLKe7k39LpiAVaARF7Qhl0ZrEE=,tag:JqTuMu1HJ6b/HgpSBaI7iw==,type:str]
  garage-rpc-secret: ENC[AES256_GCM,data:JDyBy2R7DiqQUR86MVdrDoIUt7PZ5XRLmU91xU7M3E+xnrkQeYC0rbLURmJZJp/R+ejGfRHdOWoU5IId88Z2Sw==,iv:SJFq6jO+aqV9hgpOf8cUkaVzWyas8oBkq7OB6/0ei8Q=,tag:H8OYjGNXgo4Gqn+Dwa3HKw==,type:str]
  garage-secret-access-key: ENC[AES256_GCM,data:X5sdWrT6ZhadOyOweekPsYbxj12pzRa+oge5fkgHYD7DhsWAoM6UuiAwqabOuSdMilFTXD7uVYy6w0RGuJGO4Q==,iv:zPupWntOHCVW9BrR38ocbqmEV//lj2+KS2EuRkyeGJA=,tag:JY8+mA0egGEC5+px0ZRZhg==,type:str]
  jwt-secret: ENC[AES256_GCM,data:j/spDJWtwECpVbZ15LT0FSBmoskxsnOWyXQOFh52yAik+EaRDJuh1Nj5K2IsUp0rGP1dwEeN6jD/Xw5u7wkOmQ==,iv:59N7RDNKt93ULb/wQYZIJC07jxNlpYLLKxvW8EgogfU=,tag:9izqIaWL/7bMQqU/tTCDug==,type:str]
  notification-db-password: ENC[AES256_GCM,data:sYTyFOxNThTgZG/So7gQNHowQmYViyFrhA+3JEd+ZgyhzWW9ZbEBAtCBuQ==,iv:7YO2rGY7Hy7SEAc77Rsn+rM5UZwx0SRYsvII/AamjMo=,tag:w2HKxtQEHy3IpSq8zOgqUQ==,type:str]
  postgres-password: ENC[AES256_GCM,data:Y+rq9tlf7HRzgwr6xv95CUozhSoArzwg,iv:RCydZTDoTdOp/rwCo8TBaC29+37E3LiPCLXicGeBkh0=,tag:jZFBs4Em8zFlGQZbqTleDg==,type:str]
  progression-db-password: ENC[AES256_GCM,data:jrarKaLEROBEutIgONHmdzq/jfhrcDLR,iv:+fSuZPmFS/A5GVWkVLhxzsAEeGBmri0A56gS77Qw8eM=,tag:uzkwexl//8rziYRKbNSAcw==,type:str]
  project-db-password: ENC[AES256_GCM,data:gbSeowQXJLN2j4rRziOoM910UPPUe+GB,iv:cKseqa6X0LatcoAoeLN6/MlGziGjBqaiqr+++NBUCGs=,tag:a/DfBCifOWHjTHu9U2PoYQ==,type:str]
  quest-db-password: ENC[AES256_GCM,data:IR9uwSg4Qwj+S/SMu4op4F8owwkKpS+d,iv:ez8ly7GXS5wqWts6uP2NTScDBlPAW7fdO9oL1gwzV5Q=,tag:qHQbMGCdPHl1EmnF73VwAw==,type:str]
  rabbitmq-password: ENC[AES256_GCM,data:RZ9cuHAR4qFl1qaalAxW8kOnTIWni9Zj,iv:WuRvnr0xJooO56eAo1nrnIRWPqDraBbHSoKTrFDem48=,tag:pY8Ec4h9S/M0YaX1bxUIxg==,type:str]
  stats-db-password: ENC[AES256_GCM,data:DwkocPuVO7IhxGZL9inI2PZ7Mqbc7l5C,iv:bFqVI/TGH0lx4dtv6+BXi9pWEwFvlW5LtucyVGFwyHI=,tag:cnUidobM9M53hSWQ32UGaA==,type:str]
  vapid-private-key: ENC[AES256_GCM,data:nlD2cqhqBgC4MFNimqqRoceuycKjfznN8lqF4aJNPTyLIemQ2RbZIZEtkA==,iv:TT5tvN2Ka2V8u/xnqAosHTgQOI4uQ+wJopSYSKc+KZM=,tag:KnhbJQX51lbF7JHqqpg2SQ==,type:str]
  vapid-public-key: ENC[AES256_GCM,data:qB0O8Ys453rQ5zcVwxUxRaxqc0UjQ36fQgf5oVQ/8ETqvK4VzviEnrSkoaVf+z80zxTpP/Fj1i13IDJJYVaxQhhGc96y8RF9F7pnFCcv0AAceJLxumy7,iv:fVVQsjvdY+vnB7zJc7PMl7EqoAbLlEi3JP6f7mTsLGo=,tag:tsY2IKaaZ28JarUbkN/Uwg==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMVVqai9lVXMwVXZSS3hJ
        eXkzeVhzNFd3dFg3b01mandLakE1U1cvNlNNClVHMlIydzVSdFFLQXVBNnc1Q1BD
        QnI1ODhsQUtQbFgyTndaSWhTN3FlaEEKLS0tIEJrRUNzd1doamdQandTNFlieWhv
        REJ0N1lQVHR1MStVZXB5eFBjaEFERTQK74YI3aziLwfN89mu42B5l1bo3ROFy2Sa
        ocLvHK5Uus06Bb4lE5Z34Jyo29h8r/YZnU6i4Eydh4y60/wlfubwwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-28T06:12:55Z"
  mac: ENC[AES256_GCM,data:AXb1NKfhibovhT7p+npQ3A/LXUU6tOQm+kPkQpT3JSHnNA4Yc9s1xvAZB1DDsD2JVo2ff2EGbKYHy0czk4fUtVqI0jDXagdn3a3yh6k3F8gfxIxm7MbKeHU69SB94AEEEkAJz3k7okOmdCozIurIRhpMeR13Wp4DZEmU36wuDRY=,iv:3hogq6QzNi0MSJDK+LQHqFsSVh3XzP+TdlGo8dVSkhw=,tag:yYkbHozWJdOXbcWW8kMXUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
