apiVersion: v1
kind: Secret
metadata:
  name: questify-secret
stringData:
  admin-bootstrap-password: ENC[AES256_GCM,data:ZZ7hAXj2cxlhTjNe6apeYDV+088ZMcyp,iv:lZRdHkId3WpDkdblXYivqv7DJGufE59FHAMEYJd5AiI=,tag:1/BnGoKX/IsjRJh2WpNHVw==,type:str]
  admin-db-password: ENC[AES256_GCM,data:G4pBSaLuy68cVWL5v7Fsgdkf/xBDAiht,iv:ZJVh83yhV0YO5hZeeBtaIIHP2rh0hXaRfp7CFUg9o50=,tag:/TIX4PJtKXPMHk4igz+Eog==,type:str]
  admin-email: ENC[AES256_GCM,data:BRsvJBlcOLQJO8qxAMf5Ro8eehg=,iv:SYOcR+AtL7IpBog/BOQ//Rv/YmqR2RqK/tfdqvSLXQI=,tag:BtOZqCqKtJKgFcSOZmz8dw==,type:str]
  garage-access-key-id: ENC[AES256_GCM,data:zsGcC1Pbq8d95PoWuQz2yCtO9obkzFRcIVs=,iv:00lpF/feRPCyDoSfci9xTM7N/pTYFzv070R1ZcaRPr8=,tag:axZBrGbF+2ZSXFezIgFgMA==,type:str]
  garage-rpc-secret: ENC[AES256_GCM,data:MHaTC7qeWmUpyXddLLappGs1gcsUHFgix5Q5KcaSs34UWvEmSmUAj0KCl+dK3XEmSaAEQRQBeGRNKCWXUaOb6Q==,iv:GNYCBPnC7e2Yajn0Tjd+V7WQVmjZS2vQgpTBYux/rvQ=,tag:oD1orvPkFNp9uwUGFjlDNg==,type:str]
  garage-secret-access-key: ENC[AES256_GCM,data:MnGS89s9EV7374aGqfm6NjCGsu9urFVQR1dnNtnWxI3sTEdZ96rU5kUjqvosIl0bnMTEIIFV6FVDXNQv6C0ISw==,iv:TjwhLwj2cX4gJznJOJ09/dHwQLhIFlXHqIsylkWHqv4=,tag:cof2RH1k+qTEp8qxBETS3g==,type:str]
  jwt-secret: ENC[AES256_GCM,data:dhBwtoU3j9mFoOl4oqPbf9WLF9FQ1QZwYJm7QNW6ao93SyIBRn+GyU4dM8iNYyQYoZOPXN0PzCZeLQD3JbWvRg==,iv:zMUKBGJyqZ2+sSTHcLRe0uj92mv6nkKbNRLgle47jw0=,tag:BafUFFupAc3Sxzhg5GKNog==,type:str]
  notification-db-password: ENC[AES256_GCM,data:Tk+H4RKsumAN5YTjuvHk8vVax14mO3q1ZeXBv4U5DNnRBKUtHcgWnZsiKw==,iv:nlmCDuwZOEyZg7RBug2aY7oW51gWFEfkdPjd6f1wJKA=,tag:KzLFxcxsKDDiwPeyMIhKrw==,type:str]
  postgres-password: ENC[AES256_GCM,data:3svTu4ypvXn1IDMjMf1O72+0ybxcVfXU,iv:zNLc81eQcrqV7KmaXXmXXXCgkS7tY7myPpPB0uAkKRg=,tag:7y4M6AQdsbLr65zGbXA3sw==,type:str]
  progression-db-password: ENC[AES256_GCM,data:56PqxY6c6ctniZbVb48jHK7RdBzHAtcv,iv:2egzmvUNWoutFlxsPvthxGU4OrLtOK/XG/ub/n4dyQc=,tag:E09Lh0WbB6WfII0v0ewKdA==,type:str]
  project-db-password: ENC[AES256_GCM,data:z6fAmycUBCuZhIDPfArpTb5EyNrrDvCy,iv:MowLqui8m7TQhUA/5Dclyf+/JC0jxRtsvRtB+e1x+8k=,tag:LgbH9GCg+PQJqjN7wYH95g==,type:str]
  quest-db-password: ENC[AES256_GCM,data:dNsXtMwpKnJp1GAsVfjKEiCesusFlDYP,iv:udNwXIFbC7OPaDAkgXrsSQ2Q1d443yuUE3fXvWNqBWU=,tag:iWD/uOT7kz75YYL9FiXQOQ==,type:str]
  rabbitmq-password: ENC[AES256_GCM,data:vN5eZoPJXJHr2PLXlOOVkwbZYQQbDuc6,iv:UkMHN5mLR/X0wNdwhq8tgaVAMp91R5d9CGPr7dNZAvc=,tag:PwA+EVoB0eoI000lnPEEFg==,type:str]
  stats-db-password: ENC[AES256_GCM,data:tebBkWJnQjQncWfGzErGpT4sk4ghyuzW,iv:5UgkVwDNzo8aOBlvuzWeZezjoUvXEAXmmPFtEYNQZSk=,tag:nU/a4rx0hjfpSPG8oTNHHA==,type:str]
  vapid-private-key: ENC[AES256_GCM,data:FZfC4voT6m6zBPOlVtSB+fdoJvQh8otm56jUq5Q2htWGdI73zDFAHkxcqQ==,iv:cxOqpBBMsyZwS6K+XP8yK2tfIUkRB6CiiGLvZGny39o=,tag:lZCWWuwcUTofzIL7djh8NQ==,type:str]
  vapid-public-key: ENC[AES256_GCM,data:kI2CIDsYpchPhYsvvp2uWjijUg4L+wZWykzXoSQ6uhrczAkXlG/54ING71Z6rEj+QaPaRailTMeyzOd+dsSG/7KCzbiDiGW8Op40T61r/ho4K+k3b02e,iv:vMX5DiIv6EbndE2xslEWKjIz5c3daIttCnYyNBN/o2o=,tag:xoMymSTzcb8aelRLRzwsrA==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYk5zTjVUWDBzNGN3WGR4
        SGxtWFYrWG9WWTdlUk56a0g0eU9NV2VoZTJnCllTL2puaXp3S2twTFdGenM2ZmdD
        bFVCT0QrVXZTd3VFMktTelpsajJQSk0KLS0tIEpCeVJBMkdIQUlTVi96WXAvVjBr
        eEExOE1Cak1rRDJOSDZ5cmdjQ0FsMkUK6zF2ltfATJFSRNWRk4hDxZHGS4mSJBVU
        2QV5CwmqzHR89sQDkBNLW/Ua+QchgiCIrPkz7Y6Tsv/bcGITWulBmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T06:27:43Z"
  mac: ENC[AES256_GCM,data:2RZSjIFPqmhKKrlOCSNKfKnHJ7esO4BCyjXS0MbK6xokZMmosDRW2kOEyXqdHO693DrrZIqI53rkpV1tNlqBoXw9SHlxniEXRPJPqmwltuRQ7zbhKiLGQdPE4g6Ow23C7UVVgMZcGE5vmwCybPk/BSz7x+SvIWjTvzBkpSVAPrg=,iv:3ygvjL0hldknfvwCoiaDBxxgdzrWQvNHC+DvDCAdkbc=,tag:u8Z4FhMQZPjioFAe/ZVCWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
