apiVersion: v1
kind: Secret
metadata:
  name: ollama-secret
  namespace: ai
stringData:
  OLLAMA_API_KEY: ENC[AES256_GCM,data:pZtTHkEOVuk8w4+YvkBfJamV0UsmPofiOLTKTyn8XnjDnA4lWlaJ8Umdwdd/rq9tUCzJcv5kyH5GaNOBWe/oug==,iv:FytSYw4FDZ+Et2/5DVSbQRXEoPL8rSSIZFZxASSKTno=,tag:7d73/hHzPe8ANjA31ApqIw==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YXVvRmMyM1FKVEpHV25W
        UWVjdnU2RUZITTlFY09SbUJTNWQvaVNKTldNClR4S3liUnFxMW0ySEhRdVFJR2V5
        N2pYUlRRTzNoSzllMXk3VWVGWStpakEKLS0tIElzbWJPRlZIcmgxVWVxd2VXUStG
        Zmh0d2RNc2xlNU53a2xkd2xGajNhMjAKoQ6ti6bX1KAoDY5x+J8O5fto9hvQR1N0
        DhwKqMn17T04gt2YpSwekm+/AW5TtIklv9oKv14chi7ix0HZUWGzRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T12:28:44Z"
  mac: ENC[AES256_GCM,data:4X584gXjCnOF9aBgWd1L9bZye38YJ4OaeG3a4ocB3+Kq0ju1M0xMWCGHsPI5DyxWToXRe+jTMEiCQVLWszwipjrLLar4EXxV9GKDjS8oHG2OHzRlHySW2OGr/K7fSb9ow4maoGQ4dIpT253ACml4Z2qYK/zzDteblKZbupl25s0=,iv:Dywa9JgRpGd9eKb6CgQpkF4DxMgHXdmus90A2Dc6HrA=,tag:PNcdjpT7SClt+igF493SBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
