apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:887Dc/QSxvBfLmfcMLgd5Ejmo4Xm9olCj7s/Oy763xBmvXH/7L3t9FysqJCO6ATuCVOKZc5IM2RY954zjJc7WQgqcO7Z27VE/rlL0ic5gMp2jYUDUT4rDJFNpUlwSP1xnsGIXV0pOJ5oxpPIvTbJ3lSp4uNrI8saDFl5DhYSAMk/OpZx2W2fhYOpsTsBfHMDU55SBRW6+2VSXcmTE43uMXqtyQgyS8fYa11yjA/FVo5CHkMcOho+/Lfqn690gJKzrB1sv7KOdGdaFkcHIAegx9DpG8Badkfs7RE+ZVcDDc56qxdhqe1sX5y5+HENIm9wH01eTxekmRQnhVZNKaW9Tw5NyDdS5/jkj7cQ39EdcpSuZgVc06CdbWTqMRuV24Z+3EQqrBXi2GEztn7oPtJF2TeW40dFnZYniVat9X4Ih6t3bOD8UtCHplStSnVVd11eK6IeK0ziqjgre6pkT7eKf5oWJ/U6es5oLTFsfzaBAY9hlcbMH3uUu07CZnozyC5HIDb7ZltRTuJ76j4LzzERykzxOFAK2FVy,iv:m0bkFHLbASjQau5/efFiIHQdhYg6qPMcNAHd6NsVLDQ=,tag:C6sVmSu/XoZnggOapnHhxQ==,type:str]
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: latex
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbXJlZ2FVN0dIMkhqUTlr
        b2xKNytDN2p0dFpNV3hLSElwK3QrYm00R0hzCldsY0tvMDNLYlBFRVI5ZWtlclh2
        RTZxd2s5TGthYVUydGhtc1M3TXJDWHcKLS0tIEJFSm9RREE5QWI2c21CQVNmeFR0
        Sm5PdXZMVUp2MndJang4VjRQcFUrU3cKMhWkwABS5ZXgMs2r95WMWKebldWsxIqq
        Pc7v/ai1eacgeZJ2JxHo0i9w3cEhJotWF6WtpckCLNE6TybFLBEjXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-25T12:25:28Z"
  mac: ENC[AES256_GCM,data:JY2Gq1jpEC4LPoM3wLA0vnJabRJhfGraYFPdctZRhJWoYG1g8SkWdOrGyXDhIuyQq+7xfBRU/PTQKyBb6EsjsImqnLVcX5KbZ9kCEuZVkrNo7vsdjdXVvvS7hCldzA5W+Ih7JVN+cHPBMXba1q7Vxu2Tdvv5qgoKi3R3bC2AFQg=,iv:0MGSZcHjfl7wcuFDgg6bRdAawqo4Lbs8Hw6Cv+hW2IY=,tag:xBCDM1eW6NJ+Tsiu4EgRWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
