apiVersion: v1
kind: Secret
metadata:
  name: latex-code-server-secret
stringData:
  PASSWORD: ENC[AES256_GCM,data:ylV2W5+ulTabCw==,iv:S5QAo5w3IYasV0nehwVQgtX3Y1i7lTD91nF/Z7NmwFM=,tag:aw6ZiyCHm4rnzMUOKb4Zbg==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cUM5QWZoTEM1bXRLa0Z1
        U2JJcXExVHRBMkJmMnhCUktuV2lGNmx0ZWpVCmdsLzZFTHpINzYvNGZJZWVZbFpp
        MHpOZEN3OS9lakg3K0xITVBLUnlZeWMKLS0tIDRpWERJaTdhNnJTZUsxbE1yb2k3
        MlZQRWE4VlR3cjE5eXMzTmNIb2w4eTAKkiDwBEt1lUL/bkDbBDV06CNufsW5ni6k
        cu0HBtagCPZa62MV2F8xMzczHaPn0wHRlsfSLjZIwxK9z5LnYirEKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-25T17:11:13Z"
  mac: ENC[AES256_GCM,data:BqD5EG0A/PUqn764WdPwUj7+xRAi58MW0zKAxYNA3MYmWWmWxcnsF4/PvBVRdkyR/cwE/GLx6vZwuUFUT+T3J+eMHwfqJlGyMeqNz5hceL4PI89QzZs6ncsmBTNB395D0se4O5CNShapO02SwzPn+tDfds19tOUl8yP5uoUJZMQ=,iv:19zG/6wDdQb2JdlezqG2ewY5zif/Nc1nHeq+5GC/5JY=,tag:lPwu9Z/GtwNG4wHMrQ3alQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
