apiVersion: v1
kind: Secret
metadata:
  name: latex-code-server-secret
stringData:
  PASSWORD: ENC[AES256_GCM,data:9/uRUtT/KD09QZK2N6lTSas/nq+EC7otEcxQXRcJBKs=,iv:9WS3h1gp2ADL6tbQUZA+4roONm6DfNpdZpFPFGKPP4Y=,tag:NUycb8GOWjQDNqhPgcsT3g==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cUM5QWZoTEM1bXRLa0Z1
        U2JJcXExVHRBMkJmMnhCUktuV2lGNmx0ZWpVCmdsLzZFTHpINzYvNGZJZWVZbFpp
        MHpOZEN3OS9lakg3K0xITVBLUnlZeWMKLS0tIDRpWERJaTdhNnJTZUsxbE1yb2k3
        MlZQRWE4VlR3cjE5eXMzTmNIb2w4eTAKkiDwBEt1lUL/bkDbBDV06CNufsW5ni6k
        cu0HBtagCPZa62MV2F8xMzczHaPn0wHRlsfSLjZIwxK9z5LnYirEKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-24T17:43:31Z"
  mac: ENC[AES256_GCM,data:loyDy+lcbKPLCZCHb0V3qQYq1RcxM62DA6heEUEGZq/htMM0hsp/jaOHsObgl4wm8L+NXcBX4EbZqU6Sdc19DomFWC2Mggun3gxTk/fSC3p8Qo0C5c8WjDPLZgauqcbbxAsk5t037Q22ZmFOL6aGZ5sXlRlyeWAeybHxJ3A3suM=,iv:gfE9DYKWztxsxAbzIbYcN315qSxxmZXNm/HXwqi/SD4=,tag:66WodY7A4RZsrjdPsp+Lpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
