apiVersion: v1
kind: Secret
metadata:
  name: mcp-k8s-secret
  namespace: ai
stringData:
  MCP_AUTH_TOKEN: ENC[AES256_GCM,data:eiuLUsM5pLA3XD1IzIP39fdI2QIwLNwqyN4vcTd/o6+5/m0svao+9AtmqQ==,iv:aUfqFDgzquwLYJDiU1HDNqoQXuCIIGUYNdWmT6y4/co=,tag:V6EjO1yS3L4S/jEmsWf6CQ==,type:str]
  GROK_API_KEY: ENC[AES256_GCM,data:/Ts6etGg1SK8wFz+OwalOX9PuQXdg80erBdtM0N47vb7bT4gioQQYDp0cX+1ELFD3flfxb+XkfI=,iv:jEy8VA1TRf5kmVH59ue1TaE3BGUjvHDRqz6HTA296uk=,tag:e+xZfHR/p4+ms4hfGL71PA==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SVoyY3piOWw3M3NBdGtZ
        elMwdk1OcHN3dkZrUUxtYlZXSVcrV0hQaGx3CndnbFFIOHVONExJV2VPZWZucXpS
        U2ZEaG44Zk9zbVh0Wk1laDI4aUJUVDAKLS0tIDZ6bEdYWWticGpxSHVNakpCelB3
        L293dTlUQlRUTFFyclI5UnpQWHFqcFUKwAE4IxKm3Ykbh1UTvgC/raQQeGjcBUhy
        Viu5GgTCyF7kxUguQMP7/zIadWLVeCT6YXGFZbBYxhb8S1eY/RcSGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T11:33:14Z"
  mac: ENC[AES256_GCM,data:dj+VGfysYbPgh7Q5t6ftHVgQph5Teejy2O9Kzpt39xuxUrb+0Dra70nM6lpRH1/un5PtB3suehe7sSpNtQc7JKVozc2bpewkOHTAVk9c/9sv3ev7ziLX3ql/jQBHEYN4TBBxpOzVr39seoiQ4QLF4OI7WEYlR5MHmWClRiyrtNk=,iv:b29z0IW8lFL2w07xcvLqpgIsqN/nIlr8CzTI/+jQgx0=,tag:gu6+Cr9khddh3MQWovod4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
