apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:vQQImEqSbBJLNrS99Pj7Lvbk6io/jGLAFATSFSIzQwwEhLJQtJcvc1274FYgSeTHkEiMsji7Xp6AhxJcd0M9QpwyMn3cmBAR2goLu2x/L6FmVZ9+ZZwMHUJ3/5T9XdYzVyohEiOj+5cqfL03SPf/JWU/V9aurw==,iv:y1S8cXm9UJYyhAz0yMTiKF4Uj41I3sHodpRxhtb5JTY=,tag:LzYdA6eqg7gTKQePemNDKA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:qdIs3lGKbQ==,iv:q5DiiQiZWcsBDliGwQjtjdCWJv9rmBOI0bpv4os5Apo=,tag:ccSwY5OxbL+/jON3P2cNCg==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWEVGc3JaQ2g1NWxQcU9h
        NEx4K0IrUkhvclV1SitFbGZ4R0lkK0NFREc4Clo0R1RiRlR0UkFDMkhPeWM1SUsv
        VEE0U0hDU3JGaDRMSHprN05sUFhYV1kKLS0tIFBNeExiTFJTeXRNT0hTWHJ2TndL
        Q2NkcGdFVXVTQ3dsWjE1VHhVbkd0dWsKbfzv5BoxVSiyzbqgn796zUxx/dgUWhxq
        S2xcEu3AHG1BvF1pW3hmmNrzB1Y0slD2kmm3wvkU9Igm9fTfq5D7kA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T10:17:32Z"
  mac: ENC[AES256_GCM,data:OK6vulqqGQn5C00KYqpRlgJMwTorkv5FxctjX+jpkgcgfAsu/zabibGc65jdtEvCCg2jSKF+xvncNy8uU+8OeoCIjfVJqrZnuASqtRSb6h0MjWcv8yJeNyJLCjJZI9+i61kwHX79Cble3J9xd8GW84c74QYPwzbvyOv7oJj9HtE=,iv:Ch8Yx0FZzhHwo6vv8h9vqEvKqP60IAzZHNanoS9OyNw=,tag:r5ecx+/wZGBksP17ke20zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
