apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:TYrMvj+CtmKIEv0Swh7gShmG90hoTLXXU8F7jcziZXn/8OBfw7HC,iv:1hadv0oxoDLjPtCY73rhEd4O9J0592Oxnxs/UfUQEuM=,tag:jgA0IYcrOF3i2iW3Yq9Plg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:PUeF4fQ7eA==,iv:t1ixyuxQBTLpoYeXCol3xJ9lZ8dTuXDvM+gAQMyDTwk=,tag:GGlqg8VaumiYSM0qifb15g==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTU9BcWY3cThMNEdEVjNj
        d2h2MHlBMm5FbnJHdSsrMkxGS201SmRTNEFrCjg3OFVyTXppRFY0N3VobjNTbG00
        NmdFY3ZuVzRFSDd3TFRxRTVtbU9iYVkKLS0tIEt0Z05QOUlJeGwxSFo5eUNxTnAr
        eWVlTDNmaUhTYUNPbmcwZW5WYXBUQVkKTioGRUuv5zJn1rXAzeb9qj1OxIlxgsNp
        CDURTtm76uGDdWEjI95RepBSj7XFhC7F1KKnWEFIXiTa7z5Q9GIjWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T10:06:31Z"
  mac: ENC[AES256_GCM,data:PHlJAG/irSThlkVywyXuHBk3m1WwZlhcVZDEobC489IcTiCtlsJa0OvD75O2Sh9ehTdjJeoEDZaNZgQL5K3TaUA0zt0Jdl9Q+DfY0WxiTBNXFMusFh55imc+K4wNOpi8tu775QE3Af6xKUV4lH14ZL8zqnszrerS2jRSr4sZIeg=,iv:9spOMxu2XTWKq1LSUdDhVJItOur16tF7+TFsSdqTUWk=,tag:4rKWZGzdaLBS/Ntl948vFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
