apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:1fsbUTpBHpyxnY3CLaoAi3/i+SF383/mSgrBLDvqBDZ5gcmWBV8rvNjKUvzh3kOfuZgEmzA=,iv:PQDEb5170Izwdu3t5dDfD+z057LRBbOyVOTToWApdJE=,tag:Zan2sG/EfXd4BMt/Jsi9aw==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTHJMUkp6UkRqUlhVVTZN
        aVQrZ0JaVWtFa01Fb0l1YkpqcXNTeDVXNjJnCmdnZHNpUGRibXJGcm9tK1MvU0ZX
        c29BYWY1Ry9aeGorb3hZVE9Ed1A1bzQKLS0tIGRGQXhPOG9qRUlNdGFqYWNNNlZZ
        eFU3clV4UVJNc1MraTRBbHNVTFV0UmsK1WtgbvMsX0/bnIGALOkiaf+mI+phGlG5
        1J/acjSa0t3utYpanp03nkuOEWvbI9tziWmPExuc2H4YKllJrLML1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:32:36Z"
  mac: ENC[AES256_GCM,data:npPtIHDjTdySZtVYDt6zx4MTzUqAwiN/rzH2CD3cmwuKGmZcajgCtwMUH4L70fUgHgk/6fu1G8o+2c+PZ4kRgjbJPT8VzY5ABz1I3g64tvgKl7CtVAQTJc1JqhkxPmi8qIja2SZDUEMZcT+neUboxcqVdrEAO5bchKbPZ+Ucevo=,iv:I7KS8V5j3LKuXU7nXA9M64y6cSkDQYW09WUCdY/C+js=,tag:3vYq6DNpJ2hUkNARaNbm7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
