apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Kt0O8tX78fMNVKTwAvDJRN3szFTTPxpaxWrVLg7sguRKZw17pfri0RUb46TBjtXlEAazYLM=,iv:A5tYauez/RFfjcWuJ5s0DQiLeimFLPfs6JdrBVyr408=,tag:8nZh9xhGNCyFvVvZAvASbA==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOE1penQ0bTAvVmthSTZG
        a2JKQmNERURNY2xaN2hnNS90SnJRVFB2NVRZCmliRjRTNlV6c0pXYW14YnBDMExW
        TmxIeVpBS1FRU1NvM29OL1h1TW5mKzAKLS0tIEhTOGp5N3J3V0FoVC9meng1aHAx
        Z0Ewd09aV1NDQUVmSU01NlN4Wlh1SDgKt4D+Hi6omeejhyNjI2ObGNmnaPf9D/EY
        KzL0fCW1riFXtlCoYCvPuj7Kl04I7fDCPSYdH3eWFD6rA1CSVhz1/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T18:59:03Z"
  mac: ENC[AES256_GCM,data:qv1r15MfogpXYfuhx4HB/0+052aChZRixFQherzjcAalu45EllfSaSeQyYXclESh3HYjAFtdX+sgsfF5S5g6ie4CotxyqOPQC1LvefzjjXy0V5pWQryWI1fBdaH53fjCwn5JCeqP9jXieEybCIQRP2tOVzyToSG0fdg7pBVPsWo=,iv:jq2xfjBV7tDWKms3EXI1NxX/2mqtJr0b56LsN7/AT4I=,tag:u1sbVYGvt3J2XUClQSUmAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
