---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: squirrel-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  bootstrap:
    initdb:
      database: squirrelvault
      owner: squirrelvault

  storage:
    size: 5Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

  monitoring:
    enablePodMonitor: true
