apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:u44aMWC+Aoc+gTkFH/8=,iv:6DF3iIQeq/syYQU2NHv1cfx9RMeprS18Vpt8TyUoB8M=,tag:WwtYNuMcU5tnuEP7g1DInw==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTNpbFZ4S2FWd2VMZVlC
        Rm13U0sxUHdCdHpQY2dEY0VrMmQ1ZGZoN2lJCkpEYWt5dk9zZ2k0VE03RmNaNXZ5
        NUpsanpOZVBVZmVKdGcyeTNTcTAwdjgKLS0tIGtRc0pYdENmbzJYVHFSNk5Cbklt
        WUpUWkFvZm1xM3dDSlFFWTUzNFNzSGsK5tjIgRIxCpFhS9y4aY1rhOwRcTUVaQuo
        ZFDTcMGphYmwlo8UwYGVeJ9aDzmY4StuJp66ueIGbVSm0vyDxzCFvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T18:59:03Z"
  mac: ENC[AES256_GCM,data:mXoaCB8d9zInwMn1QgAe8aBRoEAWVKp4TaTGEmaiVInL/LGHfI20t+YluwWoRvXxQ5yc5sCeFYwe8c1TAI/AoXOeAK1FmxmooKeHDmXs6y5urUaG824bcZv8O4ua9n1fat/A2SAq73v7dvgQAB0KgAm4dE9ueLh8DKPILQROqHk=,iv:UvGHN7kO1KVL5JkAyPwEnKAuhpMpWbi5cp7zbyzJyKc=,tag:jLfqAynZ+s5jlzYbMdX99g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
