apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:NIElQJYFwdc8CABIDOE=,iv:IPDhOppD17LjlfoNlTDeukHCF8gv/AtkjHE9zgANgVY=,tag:B+zv4VmpgHYVHGR7a0ky1g==,type:str]
  SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:B6DoV/g6TuoRdZPoijEKnbxU+A==,iv:bh3yE8F1D+vL5brTIiBERw7CsW/ZwLbodLTq1BGPBHw=,tag:nYlwKEgGOg9Hdxx2XxGtyg==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bkg1bzJleTNYU0tlRjVF
        TWFTRmxFRjFlZHBZeEgvWU5KQ2NtWkdyWVRzCitHYUYvTVpUVXd5ME1hRDhBRFpx
        NjZCVXZxQ0dZR3hLU29xcFpML2tHT00KLS0tIHBVQU4wbkNhN1ZmeWZZWmlWV0sr
        UkN5Wm9jL2JFNE1uT1d2eXVtQWRKeEkKR0L5bPDrqqsNTv3BXC5MDDL4bnOZY95m
        Al8tIjjfM8IvkeNS0QZba/zVkn6WFvEuvopby80Csg5txN6c83ayvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T13:12:58Z"
  mac: ENC[AES256_GCM,data:yiXWD10SCtHBrIj8qNXA6AQDoFZTUOch4IT7LIbmott34jHvL1xp5Khx7GAMwfNrUOe10XKUsDRq1is95QvHlW3gmVgT5auxrdcXFFkrN9jIFz4aIi4dejRCv0nKGxCibzOlJThiCF00XJM+o6HuhQuwStCNqMVF0vcbmzob1k4=,iv:l1c9kLwDoEsmIHoNzqCc+5WiHPdsi9pLGo8oYJ2qxNE=,tag:iL8mpp6pD3qgdgtTEas3pQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
