apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:S8kstA3lKOZD4mrLYFk=,iv:J856o1Xo2+O0Ob8AwQ0eP044Nt0VswaxBDBG9nPquHE=,tag:PuYUz/xfKcVnK3tczfy7TQ==,type:str]
  SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:XKU9P+woQzSVdkNC,iv:KD/bmxk5e+3cbfqDH0DXg4xosZ+YnrQrxIj4cUj3NhI=,tag:qpVtZho7TtMbb3zPFZLKKQ==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTGhSL3k2SC9IL2FQdjRv
        Ym52a1laTmFwUFNITXZESkhJRzNBazFRT1NBCmp5aS9XSnFBNjRxRVBCRVVwK3Vl
        aDlhVlgwclFHMHlwNUloT3lWMVVHcncKLS0tIDV2L1RIYlgrMGZzc3d1RGVkNmxi
        L29UVDBCTmxGRndRSERaRkJmMDNuWVUKSdj+/jRPeirfzhhYZKgMyklOnm30vEDn
        aGgVnkbTW2tJhk6WalkBsmT1kvegx/hKPCazlu0tFpeJ1SO7S7Rahw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T12:40:21Z"
  mac: ENC[AES256_GCM,data:HESEhzIdANEuq0419EFU5sNR6o3/RfdcyieeqUoY6uhY8oiksW9th72B/WG3IGbMFqBFO4wuynIHuq0X1uVZ3hGbnWZbdIGjIzqh5tOharieFEKsfnvbxU8dXQK8fzVkZQ8q0xg1/+avATXO0Al//yEOZymJVNYQdOYrBafsbsw=,iv:GFav+FICz6f9QU7wM3GELUF4kR4lvCvq0dM2V+qu3BU=,tag:9OfljOv+yH4eb82eUdwjQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
