apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:vuxA537b2QsbVuf6fGhRS9Kl1RA+HtJQGHvwh/pA+WI=,iv:iwP5M2gcbp91Ukq6w9XwrYL48oCs/x1HvsyNpUG8jcU=,tag:4X3nlNqj8lJMYetYBxzLbg==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrakZEY0FvUWtNcnpGZVQx
        NEFsWE8zT1ZvK3phMkhPbkltOENWV1Rib1NrClZpZFZRUnBpVndROTlweDkwc3NY
        eHdqWlZxdGhzeldQYnlQd2NsVHdmTDAKLS0tIGdEOXFzS1ZoL3BJVnNvb01DakNU
        S2kwak5rK2FvNnloWVdFTlJyZTl0cncK34BOxd92M8yhp5/MXTkRaP7Ac47P56jI
        bFYnAjQx5t5ONaa26BPLSMpAGD2BJlZT40t0JNOZUvwp1zeB2unEMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T18:59:03Z"
  mac: ENC[AES256_GCM,data:LXgBzhpj+tMQ8I94CliL08g9K3I1qJ2nAYD67b9B5V+SJ9AbZ/I0Vq4fv4NbTmFt/RTUCAHY6r4QhppEZo3YkjGGRTfB+YDMohc4ruy7nGBPvIwHeqqwx3LPrUoRFRTyQ40fzVF6vTMoVAe8lY1ZO4jlHbN0JU1qKxjIDyoyvUE=,iv:eadNPzhzWdHmPHZdCsltobyVU8rKmCGdSk0HXgW87Zs=,tag:U1esTAs7YlvbUqtjm80JPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
