apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ijH8AZ5nprdeitQwQO6LVBRYfGVub2WZ4MM9WowEcxQ=,iv:MdxvlGyhIHq/XyHtRe1mhWQGaoKiCVxdvp+0wmVW4bI=,tag:2AmVF6RssaxJgAyLnFGhsw==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YnZ6TjRZZVpiSmdINVkw
        UnhuaDNlbDU5ODdnL0xRakxHaE45ZFRLcFF3CmFqWFVUbmVuUG9MTHFHS3htYWx6
        WkhtR1FKc24wQmNqa2hXVUU1SmdxcUEKLS0tIGZ4R3FhS05mZGFWSE1HS3F5N2hW
        V2RydUZZWWdaWlQ0WkRlTTBFY2F0ZVkKYLoSsYfzUrhNKxno3P652NrQ2xKW0pQj
        RyxrF2KswgHIVzQ+eZBZiaqPb8aoBAtAM3XwgUu9Y50jDj6aOwM85w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:32:36Z"
  mac: ENC[AES256_GCM,data:1n1YiJ5pwUTi1KifSiZ4EnPrm2Np/Voh4bwOgEc8YBjsAxz7DRtxVEybZwnZLh4h5ASymmstHie2fycKwwA0gJznNqOlU8pCii9TNO9Izdc+rrCoOyddnsah32mKDI33sAxb6rFJoByhLze6fUp+L1H2n+n0VyeuPmt1IxjQF+E=,iv:Q6LdrWa5jRGtUeE6yQhrPCR8B783gjxpLHpppvuEH5k=,tag:igRJpnM3NiyNGr+Xud92ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
