---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  chartRef:
    kind: OCIRepository
    name: keycloak
  interval: 1h
  values:
    replicas: 1
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.5.5"
    command:
      - /opt/keycloak/bin/kc.sh
      - start
      - --http-enabled=true
      - --http-port=8080
      - --hostname=https://keycloak.getquestify.com
      - --hostname-admin=https://keycloak.getquestify.com
      - --hostname-strict=true
      - --proxy-headers=xforwarded
      - --import-realm
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-secret
            key: admin-password
    extraVolumes: |
      - name: realm-import
        configMap:
          name: keycloak-realm-import
    extraVolumeMounts: |
      - name: realm-import
        mountPath: /opt/keycloak/data/import
        readOnly: true
    dbchecker:
      enabled: true
      image:
        repository: docker.io/busybox
        tag: "1.36"
    database:
      existingSecret: keycloak-secret
      existingSecretKey: password
      vendor: postgres
      hostname: keycloak-postgres
      port: 5432
      database: keycloak
      username: keycloak
    http:
      relativePath: /
      internalPort: http-internal
      internalScheme: HTTP
    proxy:
      enabled: true
      mode: xforwarded
      http:
        enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
    serviceMonitor:
      enabled: true
      namespace: security
      path: /metrics
      port: http-internal
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi
    test:
      enabled: false
