apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
stringData:
  admin-password: ENC[AES256_GCM,data:rAzMkmDwR5Wb04jFzTbtwk0MrY9NTJ7OgmGaKI2rVmzzEcxULeuTCaHr0JCDLf5k,iv:4IW0ibVc6YG2z7k34bGsB8H58HgjqrZIE1pWmD5bccA=,tag:MQaXPSMnWfIybhTpoYEcrw==,type:str]
  password: ENC[AES256_GCM,data:Iwoaf9jFBOWwin92SDYvKqK82s+vorIW3o7I1bnUl1MaGJkzz4e4j/mwc3/bXl1r,iv:XObwlsZUAuiCzIg4pt/7TrLFzsZKvJMHF3yDCMZ5aLI=,tag:7ghi42fT0JR1a2qkDQUz3w==,type:str]
  postgres-password: ENC[AES256_GCM,data:2xBKdcsj07r1SVCA4JicUtJ9Krq/mRvuUHDHt+sKrAXOjX0XAraGS9mWFEbWkjuW,iv:1FFsxkvcODLaCvFauZUZFeOEkbaugt3AM8hHgS1gpQw=,tag:ABlL+bOX35nF6fvy8+gSvA==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdnN1Q21oc2o0RVpOOUtN
        N09DNEFqNE51d0JpUG1RODJpZjlLeFdJR3dBCmFzSTVFbkJxWDYvRTQzZXNiSUNn
        bXFzeS9CMjh6OTNvclloQUtsNnUwMHcKLS0tIFpSYUJ2bHBCUldJWVFlcVRqQlFR
        Tmo2ODVpbldDL0MzbnZjU0NhRW1ZcDQKXvfNPaoWOOYUlsVhf0DGfYCM68NW7yFc
        1uguPIlAUYV/OgP+uRMuphCq4nn/Wp+YOvfnUelnYkcZ/D5ebRKSLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T10:04:54Z"
  mac: ENC[AES256_GCM,data:uL2/cuUpYlnnFF1Lf/vgcFmhh3uso1gy6vsjfnpDpAQMfOEUM+nZ0sVc0Xy8ESHut6PujK1leFrxeZnc0SnCDrJmK3flXoW8gh/Z9cLeArfZhML8lLSQwtnxal5w76B+MeE4XCglvU8vayoZCPt5A40wl5drtJ0takB14XfjYWg=,iv:zn+rM2VYXHVdl2wiVIamQVR0pnQeGMAeLjhG1mUcg9M=,tag:YGkKIwDPULE0H6c4DLYQdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
