apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
stringData:
  admin-password: ENC[AES256_GCM,data:obrlFIyR5Msg431+jXCAwM/cPL5X6v7ITXP3I00O,iv:adfOhx+wTt/ZRR26Vwge68UA2FcDAhYl7YQxPChs2gY=,tag:r079MbRDErRLln/6Fp4Lrg==,type:str]
  database-password: ENC[AES256_GCM,data:3po1l3M7th0o5EwwBUHhYzI/1Tkt523zdb0TVv1CuCY=,iv:qjUstGdxtnK5YzvJtlrVEzXeC8v9RNS2bCl7bsVdxQM=,tag:9YeP3rduyZDs7MVPM1eABA==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK1Rnd0RtdU83UVdLWE5q
        Y2c3WEZ2UVo0SmpNc1g4aHZwNWhGOVowRnpNCndYMGQ4cCtZTlQ5aWxKbE05Sklv
        YmhPTXpHOVBhRE14R3NGajNqN010WjAKLS0tIGJuV3lvQ0daanE4dkRIdkdlYmxa
        MjlpcFlVNGtZWDh0VjBWeEphYUptVGcKLNQco2FYtZbsV5H+6PSERTT87XVGXSSe
        wXijBtfS+3cg8q6WSTQD5rxHln5bKPz6pVaZO6EqwnPAPVV6qyrmiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-27T20:20:21Z"
  mac: ENC[AES256_GCM,data:kWLdLemds8Irv4qD0q93qjPCV59mjaYB1E3UHdqhCTLAN/i/vTop9+mXn6EKwY6vDx8XYL+/YHafczQCsnmWseqE9TjV6oJijZgp8cNdhfOFL8/wz9wAM+CSpW/vH2wqxoXx1xgSL/e6W14X+D2ebmoPKHP4XrUtg2w101JoWQE=,iv:MAZP2uSECrODfe0IYAkpIsvnMKm2vTYUyiERbb0SFTg=,tag:tXmimVCmf2THOZWEuuEJdA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
