apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
stringData:
  admin-password: ENC[AES256_GCM,data:0AIh0PuUt/yzMhbgDCIinCWXAwxZZtYBhWjwfjgo,iv:kBui8BoK3lHpSnIdzA7BVeJ1+liFIwNq35tMDA05GEc=,tag:hHy6bki51aH/HkqMoA8ySw==,type:str]
  database-password: ENC[AES256_GCM,data:JzeZnRaWBMIUkUkS9tSWg7hZfcmeAXZIXsmgOAd9KZk=,iv:CBnYAGlncluOC/aVpJsAmTM8Dd3qgi11I26MVSSBh58=,tag:Y8/8QNtZveXVP4y50loRCA==,type:str]
  username: ENC[AES256_GCM,data:nJj+UML5MAM=,iv:hUjOF+fTx5OmGl+osZC6Kro/ZqIJ4zXVKol6EIXH11U=,tag:zJoSdiBmW33fWLAAVPYS0g==,type:str]
  password: ENC[AES256_GCM,data:qmEAO8oMI45ReptfyQemwwUXg4/oPhJvp9MX+n+gw4A=,iv:MCoZ+F8iqrvv1QM/ny5l+j+QSggNogoYSOrN7taHpeA=,tag:3cWjnjit5k01nipDADofQQ==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L1hJMjU3Y1R5RzM1em51
        SUJXcHVFQkNTSFhPbFpuT1dmN1NzYm92S1ZvClgrbWpjUkpuQjhyYUVvTy9tYkxq
        dGg4a2NyeHVNTjNRNXFBVmV2NXRGeE0KLS0tIFdIOTVVTDJxZlE4RGlYZldGQnN6
        UmZsRGlsdUJnU0VGRlNzSklBclduczAKJ+PS5YwIaJuO3OiVO7FHP4fBjDebxiru
        Mtq4lrrKXqw1dOTn6o324J0/ujZ3gaUphMcndOhxBR6+t6HwMLhxRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-27T21:11:32Z"
  mac: ENC[AES256_GCM,data:1nquPhQAoV0smUMR+PxJwNhh3ZFnXjOz34f2xTqfd8ZBPPtza+0KAJKNU6g+yJ/ESRRwJsmed0l48l69WYzao93Vt+DgDaMVsiSUsB7dM3/wWbSA28WVoSH1wl6G8UlWpZjD7T2A/6/MwQ87GSdB/cz73R6ZxweFwL5CZR4AcFs=,iv:frKpL8SWC9wOLt0nex4qkDfhdWU6+l4yWHmJzf+JodY=,tag:moOMMyJ5jvMzskKRsH1WnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
