---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ferriskey
spec:
  chartRef:
    kind: OCIRepository
    name: ferriskey
  interval: 1h
  install:
    disableWait: true
  upgrade:
    disableWait: true
  values:
    publicHost: auth.getquestify.com
    database:
      name: ferriskey
      user: ferriskey
      passwordSecret:
        create: false
        name: ferriskey-secret
        key: database-password
    common:
      serviceAccount:
        automountServiceAccountToken: false
    api:
      admin:
        email: admin@getquestify.com
        username: admin
        passwordSecret:
          create: false
          name: ferriskey-secret
          key: admin-password
      server:
        allowedOrigins:
          - https://auth.getquestify.com
          - https://app.getquestify.com
          - http://localhost:3000
          - http://localhost:5173
      resources:
        requests:
          cpu: 25m
          memory: 128Mi
        limits:
          memory: 512Mi
      serviceMonitor:
        enabled: true
    webapp:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi
    databaseMigrations:
      ttlSecondsAfterFinished: 300
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 512Mi
    postgresql:
      persistence:
        resources:
          requests:
            storage: 5Gi
      resources:
        requests:
          cpu: 25m
          memory: 128Mi
        limits:
          memory: 256Mi
    gatewayAPI:
      httpRoute:
        enabled: true
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
