apiVersion: v1
kind: Secret
metadata:
  name: ferriskey-secret
stringData:
  admin-password: ENC[AES256_GCM,data:4YdQrzkZvW6HhfRta9nYHN9pVXRM0qVqxEmLeNPNz3YpC6xaFiLroEj79+hZDEq4,iv:07DY3LUdtFl8E4RsvuyuWENwF2zhbxZ4u6PgcqJ+aag=,tag:WQWUP/zEXSlTMJPV4S7okw==,type:str]
  database-password: ENC[AES256_GCM,data:+nY6dl4jzP4H19eVEYkM6I1EavFNdlNPdpH6+9TI2q5ZoaWtLJxCsT9wErh7tUVU,iv:X/Iq24YJ15hrLaTFRc9XdDefC3O6QKLMdJJR47UFg8I=,tag:BEFl8gIbiZtUZLLJacJAvA==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0L1lKRlA5Y29EckFDUVpG
        ZkU2RU5PTVFlZ09URlpxWkZsM1liVytCekNvCmdwdWZFczU0elhpcCtwUnBxUUpx
        NGgzam14WHMrbnRvSzRrVEpsTzFqd1kKLS0tIE94WUdEWXNGS0VsdzJPNVRBUE11
        MmwzV0xtSEtXSXNqb1EyNmViYUtHZ0kKMaPYiucVgKYieC59zUe6ZGpc4VHnHCk1
        Q0qzgbOJdtrdwGcHEJ5MiFgrr5uJne+2cwxr5XMVEGLq8cgDP0f3Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T13:09:08Z"
  mac: ENC[AES256_GCM,data:LdMZuWPUjfR2MducZDv8VuxxT3yjn+jfg4vfQt7IntOCe6WcV8t/AMHqLyYICjAOaRIBszw4KUsScA4fUXYV04RGTlxC9kysnRmqFkFaMNWNw6eHrw11WeClvAFV7kdDH73/YxbJRPa4nVmaxwHfq29NN2Oon2m8Nvvz2n3uOy0=,iv:6NPOUInRCdjTjTZP+KrCMZwYAfAeMd2IKJqYP7pd0iw=,tag:ICIx0BuQOw7RP6LcGjMy2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
