apiVersion: v1
kind: Secret
metadata:
  name: homarr-secret
stringData:
  SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:Vfywsa5WQ8H+TzdBQ+yidp46IG1Hp2yYY5ICUYn8Yz2X7m3gP0H8RA72H74VIbQkgInWxrsAC+18svrhQLWlzQ==,iv:Gpbiu0Is1qBCVR2Zq/NjKvl8ZPbvpC7eGUgm1Vp3RwM=,tag:uRR/bBt4lFNNnsX195/Saw==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV0xMREpXK1d1eUJ5VVo1
        eEFKUE4xR1VFeENWd2duR2RzQkQvbFc4KzAwClltZDNJOEJBNFl0R2FBSSsvMXpW
        V0UvbzVwNk5kR0VmZ2wxRGhZRFZ4cFUKLS0tIE1MR2RRSXkyWnlSQjJyM3pMcnNz
        cVRUWjNBNXJTUmkzUC8xUmcwTERHSWsKrupa1toITnx2n53wxn0pskGYEh6L6p/c
        mgsV1HxHede+sKeq7+GlJ21aRE59+D927ypXUDJRleHHoClG1XuLGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T13:34:50Z"
  mac: ENC[AES256_GCM,data:fJlhTGTjxmJjQWkzfe16llsNMNdWzlTOcHBSKeiI5AiQlkRxBOjt+2pKQsql2bjBa76ig+64p+9V2642EQjPe6ZrF55rF6Sbj3MjoqVYNKt3focKslkGC9adhGSJG+E4nwQZU6lvpeCxLPwHe61q1ZcAEvUPiDZJ2Lj0ogdV/ws=,iv:m0wQ5BThBqUgXhzBAH+zKgXskmjalR48ommp69snEe8=,tag:5QNwJ3fbcC+UTFsIJVD+5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
