apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:hk+xLEEb66lKun3thaq6UOtstx3xyQmkPJD94neHDQlXroQpXFs11fVu5gWcYFWg4fQ04kClkrq5UArWVBe6T/MClt0PjPFcbiHj8cHI3llUNwIJmPyI18MafAUQEWbo79nnK7bfbnkCSyvfESu8UcsRJ+DW0qbT4gL77Fx8UkNtfO1ZBel9UU3gmVlK5bsXotpkXMRjfY71qJvHEUxkAKRFMaX9HBiie3211Gp9OUThUIkk,iv:S0HJWPMKPw0wQue7x/FQCeS22LyG8LkAIBDU1NIVK0w=,tag:f0IrorNa+Sgpw2H47+9zLQ==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UytwbzJCeXRTeEtzbUZ2
        UEFlMWoxaVltZXVCc25GUGRlZndrdlFqcG5JCkd0OXpHSGo1bExSUFk3ejNpYVhL
        cFlTZGRSQUhFMmFZWmpLSVZ0K25HNXMKLS0tIEVDRXdoYmhCU3JBT215cnNzRDdx
        cHpIRkFFNXdzMC8vZUVoQ3ZqRnA5NU0KCFNzuhPZbgDUWJEJma8MakI4PSMauUb9
        YETarFEW+3m2bTCitCMu4Var2m8KajYOQOWW1kVYGpMEBtQ8Qig3sA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T18:59:03Z"
  mac: ENC[AES256_GCM,data:LWs/Sum34eCe7Axi66Qh2MSHoUpQLFzTnYn5e7Y1fbgjx9lAIe2en/wuto3rzaOQD2AwaZPwc5ZJJYPoHgDQ1X0llID17lDENwrrRNKBR8tg1/4tLZjNdt95XakopYBObXLcs07m4zRw5/VdFCbTVCgk8A/il0hep299HkwSmz4=,iv:5leLx0Uw+JajmxCJdHIJYd+lb61h64Ew/5XYyImZK34=,tag:IIY3Ak6iNKw3gG6/D3hKtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
