apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Gl+JWCVXUd/nMmL7wZrupBBOZ0gx54dCYB4jsgLkOH+Y1ReeNKrtO9colMZDkYoSgfdAc9UmQLWsPfsqVfUsKdT0LJH4E1GK6HdrvvgyssqzyZLjfiCbBfAtoytzGdVsz/btrfp+wup0IrD2SIfSNrI4OtA7q1Hj4cNLaqWNTtEVIqh4yQcr6U0xjc3kuDHdkUOV4oL3ZMi6jCLORVnQ19u0+m5HZgE817CXYF5ORw+kCS0K,iv:TJXaIwTrlm5/+XYDNfeOdTiXP5oTOdNsuUy3NHr8sOc=,tag:Np/Zf89h0AINYlTdhaFjCQ==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByek5na2UvL0JVd1dYdzQ0
        K28rdlcyMjJJWERTYTdSTkxoY0NLaFpzcWgwCjlUNHdRSnlybXFHY3QrVkZwMER1
        Y21YWXZ1V0tKd1JTNVkwdEdHT3AweFkKLS0tIFBxOHA2Z0lpZlN2RUY4MFYxZ0FX
        L1BjWkYwaGdBZG1tUjNrNmdVVS9HVmsK3+54HdKDTMzpeVwh8y8BEa6ThqoJLKyr
        3cDZCpW26VQ9nGhzv+0u180zX/OdTveYHwioNhoDQtV7RqkNFIRMBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:32:36Z"
  mac: ENC[AES256_GCM,data:aYLdC37lw7oqJQAq+yW0JzupJFtbINyXYGOnWU9q9c+yPRmlQsMo8v0aulpGXd/J4I/+uroPQ+hFYKTt4bK6wAv3AGC7kgp/TSac8wCpFXlgw/G9I8I99wt9GcQoDUoUM8GLCPrLfDvvmZtMZ6cOkVImfJ0Y/azSR/DlSGcnL9o=,iv:F37hj9H0WLl+YCINBCycOiDnWne65hkpZimF6tah+6E=,tag:Ez65/CFijXWsxiwEFJBE5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
