apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
stringData:
  username: ENC[AES256_GCM,data:FoW5MYs=,iv:0zMrqMO24XxZu7OyvLy7PJ0W7aGhEuBGQkA/sPWcWtM=,tag:QPXjJQWnr1WnBVA8WMNk2w==,type:str]
  password: ENC[AES256_GCM,data:7kaZwaaU5BTdETIG,iv:DFCo32CEp8ePLVP68bPceKFVI7txrrzM4FqRgNG+S2U=,tag:i5WIOdQd9YL0qrVm1qESYQ==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUzVQcGNyZ3p3KzFYR283
        SFFZRVp5bFpTWkxkVjlWekZCbDQ1MXVhZmgwClBFWFRWUUdGWWxZc29zUjVtalBJ
        WjFMMkhXcVJLSHJrTlY4MGN5NkY5SlUKLS0tIG9EVHMyeUxlK3ZOaVVQQnpRRk9S
        V0tUTWpILzB3bDJXNHFWd2YzcmNiaEEKJHCqtyTftHD2Mzxa2WtQTWhVQ/cLU3Vf
        vIiW+QtTVqqBPN6kpm2DV69IHFoFXmd+XGAzT6Tg+Pn4ZiHS3S3e6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T17:51:11Z"
  mac: ENC[AES256_GCM,data:iCVqQLQZ+FUNRLzyxF+iXBG4XXv3w9DfGZZyHsoHOiUyJpI8cg7vg4qY1IxSL5W+kG3SsAmlTjwnbDV0vsiABLWx5a6qb9LELWwVNnWfIvSxKBvhbqFo9uN4Z5X3lx1pVIEh6a4r3MNcw1s9kNRcFVM1bBzHWXFJ5Ik9g8AXq+U=,iv:LFPmP1oJ7IbJi8TPwODZ6I1e3HGIf5ZrdBuZlAdKisE=,tag:eijwH5ZVPMdOhaV821Ddug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
