apiVersion: v1
kind: Secret
metadata:
  name: openproject-secret
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:pGVtGve7vE+4PUrJ/Q==,iv:sHUEY/oCZblcvuNRwB5RrItZJq4RqtE/pyQ/wVLgEFI=,tag:If18CwTGbycUzX6B1UGSsA==,type:str]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:0tHf7tb3/f+LN8TxSGRUevpTp0UhvMiJNfuyXU8Da9LTK+MjxG/A1uKjylJaP2Y5/xeMwLfpQUXaW9Rutr4GcgSCK2ixcoAx84zvU5Q6bIn2yZTa/Y9iMxajljUbttA3tZaQIgdr6VCY0ykTzbCQdA67s3aVhjQLbD+zZIv5ujI=,iv:3/2Gb3AouLcLJf7WIfgu57KQ0Yh0ljjEmctE3xFaclE=,tag:iBGyJRcOZSU3/txiH9xdvw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:DiDdY8k7KSGpBhJWEVedCoJ/nUbH/miZzqbVTLaVDkfg5cSy/6bymwZGJ6r7N6VzW4UFgK5TBMaaw4eB/MMiFL/KN3r5X4BCGO8=,iv:DQB6TNpBnfTM4yAj/B4/eeXw/r/h1Ts0THD/2NqW/Xk=,tag:znpVYptMa4ETY132QkgVrg==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsKzM0bzJRSndOYjRsNVMx
        Ym14dnZvU2t0UzN3bmlWWEg3RnlGbFgvR3hFCjlCY3E5dk5Gc1A5L2hGZmkzOGRO
        MFIvb3BFSXRpMm9teDFMbWJ1UDdPOGsKLS0tIG41R0dlQmtzVU50akEzMzJFZm15
        R2luQTRweWE5YTl4cWk1MklMSytOdlkKyr5/OQFybDyPojd8BnNGR3FOQyZ+N2um
        EMj8LzWKyoefs7PEYO8niuMHR5tq5rdT2orX3iBYUveSHXt5cI/d9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-18T18:07:56Z"
  mac: ENC[AES256_GCM,data:RDivX7e/I7En32GABxeHFwK8PKq/7F9XZ0qpqo+w4iDQJk+VncSwW+m5y7ZGtMBxQNFaceAmxkmqiMKE14y1EoxGGNEOFE1LsXOl6IFuTh4pLFGPXv4UJNJpW+b0cODwGRDzIN8cAbiakUvRI6hMV838J9OZbHnQPBDYqdgZ2CM=,iv:PTqVrFsKLqthWSnkU88h7PmM5NpHj5Bc2b6xDDxKiPs=,tag:lSHw9qgd8ps2viI5bOyRwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
