apiVersion: v1
kind: Secret
metadata:
  name: adventurelog-secret
  namespace: adventurelog
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:5S476nYLpy2/DuNncxDWku71W6SKz+q55FLbntiXrL9Ge/DTSMJqAF8M/sU=,iv:R/qDjwgvLnjR8sMU4srVPZxS+ElroZDzRz64dhAAvDM=,tag:P/9uVbBtgh+t1QU6IZw+0g==,type:str]
  DJANGO_SECRET_KEY: ENC[AES256_GCM,data:nnCu2dV9BNj8MAD9jMXgs8NZpLixDK6rRjpyt/A1pawXk+/CcGy6RxCl3+LQVismV5POvAg836vNdbuVsdIpbw==,iv:VI2W/0unsQc1MV2LR4e3gbKE1lM3WqLeOR0tOMlGNOs=,tag:jU5dLFzMWtlMajd8AeXp2w==,type:str]
  DJANGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:fjnFkYrQ/OwjgwJ9T4WSwqpAIo4A4AHczVP+HmQJRN98/7qzH31Op4q5ZEI=,iv:jgEiNDop8C/cGJjob2AG4VBX3YsOHPe8DhxgWJ/awDk=,tag:zXTPLLHVJLWXdzpash/ofg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUERIV0tLOWZMcTVwSlR6
        bmw3dnZMZDVWSm9sL1EwS1VKWnNYU01YOFZzClZMRnF5WE5hUFlWbzBjZUJCcGxF
        NXcvZ2xSc0ZWNWlIU0NySG1FMU9CQk0KLS0tIG9sK3EyRzNrVDJzUWFKWEx1VG12
        WGZUd3J2bnZCS29MVldyUUVBdkF1R1EKDkItPQV2uG62WQB18ICMfGDZk2lxmhwo
        HeHZzwpUuwNJrwvmO2fMhB4nm1IO1FeCRzDRH+WxRz/KTS35hj4ttg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T20:51:27Z"
  mac: ENC[AES256_GCM,data:GC3Nrs92IZi4YwJ/9XUZnJYNyEJGUYzTz9/nY9RqpYcyWkxQTkwmFIydUPejAYJfeY5ULZEqeE6ssUTfsnhj08f8QKm0afgL8EPPq5jPoYnOBXp/RoQNPJRn++jpiEUVe0lXu9RZIcEJ/MGdwn95JWqcrtEDWf+zR/tAnop2nBY=,iv:XSCg4FjS/Ks9jJKWKLhRE3ng3oVfIkL0VecVNKVPzhM=,tag:D81MWunz7FbfNu/onBvlSw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
