---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: listle-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: daydash
      owner: daydash

  storage:
    size: 2Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

  monitoring:
    enablePodMonitor: true
