---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: listle-db
spec:
  dependsOn:
    - name: cnpg-operator
      namespace: cnpg-system
  interval: 1h
  path: ./kubernetes/apps/listle/listle-db/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: listle
  wait: true
