apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:5ibA3xHYGw5v62+uY4zmBIChbXwQPf8NZcsmWqfv500URqsACTluTtmkTg09DcRpgqiobwmFSvF0TBtM9sF/HsPgs2mnJ0nurTNBlEvjRHjZlWgqoL9EsLoR2S7m/lODqKrnNjQIryLGjCjWi5zCqUYGuuej1vIt6flZR0m9hLRYJjb5z0LZFKwpnDyfwdYKTwx+8YyachzfW3dQO1Xp4U4TKUMvH65kBMbRBiSFltOivXmqa3AqPVY1lSfSCDmE+pzbbov94LXg4bqHS4S6CM/hM/viYzq+kmyjI2nSUep8wgHVDRoAV6dKibFBcA3F2ZhuCoHK7Z8SGQZkU24QU/ob5zZl3nsoIYOL/H5ZOIctMU7F9iXNLlSs98cWu9BWqJXRjeY4TcLx3wwm3jMK/mF86ptaUmXOVN6s/2XG/WxiABIuoKEI/Cz9Tocd8M9xASu3r9a0+dkRrQYjIbPkGCW48mVnjEB3bM4LwqlTy09yFsuhS4KYQJUMEwjgr7GfGqJlBvSJdp0P766P1tdMm3+zy8R4zs0O,iv:wypVKQFBZSaUYbHB83AsLiZwn4ntCncrSZv53pTzEeY=,tag:rR3d02zwHgic+ISQjBpVVg==,type:str]
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: listle
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbWMvVy9MTGduMGwxd3I3
        V1kyN3hNSi9FcHF2QlpmSFloUkcrLy93SEhzClhsdGpQVjA3UXlzU3BIMk9lTUJD
        N0FsVlVrN3N4eEQyRkZ5ZnUzZmdSNVUKLS0tIDNoZkp0NGpnTU5lNkZnajEvUHc5
        cjRwdkVGZXhObktEeDkxV1owVFZtVEUKwM8RWyVDfk/78uPIDVjAtD5tCVyLsY7U
        tp2pKQKz81UAHMrAHcV4y84aLj8iImQmyllaQS2SoejWYitkI6O1rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-23T15:56:40Z"
  mac: ENC[AES256_GCM,data:mv8kJp5tX+K9dZjeg9nBec90oVD0STXZVLK4AMi1fneSAn8vTdpKoYpTNQqr0BAB2cli60/HyiqPj8JPTdxLbdeu6jghYDDGvQd5RVlXo4ROEfXc8tfKNh0PKh1JBZJhT77BdDfOGG9V2mKi5tnEVxQJmvHV33kt6Ahy8ueIwWE=,iv:wYXhgUWSB3/JbagT44SuPjorv8sepF65Bw1R46M91FE=,tag:41bsjwQBM1fY3KxG4pv+CA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
