apiVersion: v1
kind: Secret
metadata:
  name: listle-secret
stringData:
  jwt-secret: ENC[AES256_GCM,data:Pcw+hqaB9Hxb25IBFn2BikMPmK6Ol/L+j1uxqO1hqZ2XCmO5dU+I9hlNm9QbgNv0iw2goki8HC8kBxUjshjofw==,iv:fEW36WoHmNXWn9cK45to/3e3yWiv9plCOnczre8r55A=,tag:T9n23b5nf7JEiDDJOmI1Kw==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTVFldkNZMDJoTmNGNTlO
        Q1BQQ1FOWXZZTllJMVcxUkJDZnhCYk9XUDA0CnVJNEZWQzBhWjEyRndHbGlmdVRX
        eDJUMi8yc29UMW1CbThFTWpaZnU1a0UKLS0tIGM0VlVJdzg2d3kvOTB1MHdWZGNn
        MXhBR3RzTHJGQ1BWQlMrN2IwbTAxdTgKZ981NAzk0zLWL2sAxpnceXV/9bjHxmu6
        QYNZpknq19mUS8xQpgjgWgtBpsCHLcvtPmF4UGivU1+X+4N+hDpoPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-23T15:56:13Z"
  mac: ENC[AES256_GCM,data:yWIXj9iakTpB8zPHSykzyR3i8MjKORLNLXtmQUm2iJ7mSDLPou0E5HOAw5HqACIVYtPC63vIEUQo7MEWJA0azaP5ofQl4fHVH6n9pra14aBHAw8XOD4s8LQgdWIu6ulPiPYki1buIbE43aPWAoInRXU1a9t6/L7Xr+5CRHcFWDM=,iv:w/jJwNBEz4QCJL2rh2pZP+IEluMIBFM/UJyA2VLCEdc=,tag:Rw8kWMDO7c7yuzMbQOtucA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
