apiVersion: v1
kind: Secret
metadata:
  name: gitea-private-token
  namespace: flux-system
stringData:
  username: ENC[AES256_GCM,data:K6oKAr4DuGuDfQ==,iv:JfqAnJTa/QaUCywUNRfCJBftimvzlIV1TRB+Gh3xtpg=,tag:SN1Ky7AJ+Gup18FmOsD1DA==,type:str]
  password: ENC[AES256_GCM,data:cm6qHLJp126XYhZWL00iNduXdppMnQWBft3fya5ZH2iCKgvVHN3GtA==,iv:saszR5TKvP+3IzdOox01wdNfaJLjIAgbP2uLIYn9pkY=,tag:kiHTdfMCeIoEw3S++ppMqA==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYzFtYW9YQkxzR2x2aVZa
        ZzB0TTl2VGpKcll5dE1iYnk1MUpMS1lNdmtJCmI1d0htQlZRV3ZpZ1pJd01XLzlk
        N2xMMjk1WTUyaS9kZFB0d2lqT2l3VlEKLS0tIDc3Vjh1QW05WVlPcUxKRDJNZW1C
        NTFOajhEclJMalhGazkxaFhRUVRsVmsKcPRP9N4hglrMO6IWif3UGekEQGbGRnXE
        S2NcI/Em/byiyEUBbwmMERX9HbY+auAgIxDyBjxCtAtZ9dzO73yd4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T18:37:43Z"
  mac: ENC[AES256_GCM,data:o8f4oPran1rf1imObqlXPfrjH2UezyPBvphRU6ndcahKkah+dVATMLx03GCNtd4nrMgE64xcfEbw+odgam8pnG19PJxKVT80CpTbMqHX7VtYgZHE7Ax8dcuSfaPDjWhUoeKBizY+BcCMoC3xgsXzCoPrC+QqyRauALiQHK7bpmo=,iv:/oWC/Jq6yVb2koy/lDifX5Rtnw9oiQxQpelqtIJiuT0=,tag:Ep2NRg6pkae/g6MEIeaMDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
