apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ACCRzNPiaCV0JY8ILvgKIr2uK/aR+Ku/Ujp5+a48Bne7lw1EEMuUpFng7Ok4c9ZekmzpvyA=,iv:NuDR981qbGu9LaaLgKoJkPHdvbvvyGWJLGaZmgqD+Is=,tag:0dwHoEVE+ornrN3TMn+6gQ==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIekdMYk53ZEFzNnd2MDJR
        SE85MllBTjBpTW1VUURzNmttTEpGck9HdjJnCit5bmFGVDJUTWRTODRPeE1EaHFU
        MTZmUDdZWThLeUpMaXRjSU1JWWU2TmMKLS0tIHpKYjBBbTdYNHMzbmZZN3ljdjE1
        aVFUaWQrUVdWc3hQa00vKzRRcGwycjgK091bVSpjkklHDmzY9Np3Wd3PbUxoxxB6
        9ilWWsSfP6wBZENoHqVALW1Fo2skY5K+I/qE4LwDyLXGjmsZ8ESwFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T18:59:03Z"
  mac: ENC[AES256_GCM,data:fLzlOUqJmOFbbv+mEqC+kuL5IoWQhxbQou58gK4wbaQQH6wo/DA5OPrukETKpHJx0yhXrWhlB3QJ5iCqowjAcVGncxwd6nZ7C22xTyXsYlJp1/8yWJP8Izw7R8EoEEMXHkKeJyjePoVxTHjLNpiMpnyP2IjrEyU3Pe7aDlUcMaE=,iv:vMVXya3XUAVGw/bHtWxqtrswNsEsLjooul/SBVyeB8o=,tag:TNyR05nJnYpdy/dg2SuPcg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
