apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:L610jKQ/sFZ+uwq5uX7W8BZHYzv64YGmWg98HfJQJgNrji1Ju+VfkSxNlLqOU1VY6haFZkI=,iv:hMzwfO3/Q5VHxBFigUgW5nHhkZMcFwKiChBBY+cPo6w=,tag:lg9zykC9fKQcMl7DgdcQNg==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYkRKY2tUK1paYzROeGNm
        Q3Y4WnNKbkhEYXlmbkVhWWJsUkh4T0YvaFdrCmtiWk9vVXM4SjJKZUhFeWNNVE5Y
        R3F6OFB1YVhpN1UzQ21kMUh6VWM0UEEKLS0tIENQU1FlNi9jNnF0U0RaWnIvdGJq
        R3E2T0RTNFRjOEdpaDB6eDBFSEZpenMKt4M3WBM3MKMkSCovOF2jqjJXoVgZZUfY
        V2QCrQjmqDPVJWsMgjwy4d45Un5VcZtFcazBmhlOMctYoiIOBq+5cw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T19:32:36Z"
  mac: ENC[AES256_GCM,data:MECT6JtAEXgkaSGQENKcesOTIGe4zCkfewTPwgKRP/gTvBRbtyCXMRD8n0iRszce+QsZxRfek29WiervNHuASCHKGhrGsJy9NRE1cxWoUt31Jm9O+cymQwEcElgAPOKF6OGCuT/GpU9v1FDjEkmD0qo8ItbmD4RmEi9vguzKbJg=,iv:zHsnQ3U02/RWgbAuEy/BGZG8LsZdS0VQizn1qh0/GkI=,tag:KZizA8WFOp+AzngUzcWyAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
