---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.50:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.50"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "firelink-01"
    ipAddress: "192.168.1.147"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/25b18a561487b9b993d64a3fb9b9b8da8a35fc612ccb35db403cb87b37d24e7c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:26:e8:ac"
        dhcp: false
        addresses:
          - "192.168.1.147/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.50"
  - hostname: "firelink-02"
    ipAddress: "192.168.1.103"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/25b18a561487b9b993d64a3fb9b9b8da8a35fc612ccb35db403cb87b37d24e7c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:42:70:8e"
        dhcp: false
        addresses:
          - "192.168.1.103/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.50"
  - hostname: "firelink-03"
    ipAddress: "192.168.1.25"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/25b18a561487b9b993d64a3fb9b9b8da8a35fc612ccb35db403cb87b37d24e7c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:da:34:e3"
        dhcp: false
        addresses:
          - "192.168.1.25/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.50"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

