---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.50:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.50"
  - "${TAILSCALE_IP_FIRELINK01}"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "firelink-01"
    ipAddress: "192.168.1.51"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/76bbfe365b438b441b2adb974202a3c663b58a18beb3bfb9aab6b34bf2f36cce
    controlPlane: true
    patches:
      - "@./patches/nodes/firelink-01.yaml"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:26:e8:ac"
        dhcp: false
        addresses:
          - "192.168.1.51/24"
        routes:
          - gateway: "192.168.1.254"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.50"
  - hostname: "firelink-remote"
    ipAddress: "192.168.1.84"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/708747e350d604ae9e57227d8dcf274091453ddb1097b765d4ea8884f1992c1f
    controlPlane: false
    patches:
      - "@./patches/nodes/firelink-remote.yaml"
    networkInterfaces:
      - deviceSelector:
          busPath: "0000:*"
        dhcp: true

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-tailscale.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

