apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-telegram-secret
  namespace: monitoring
stringData:
  telegram-bot-token: ENC[AES256_GCM,data:s1x1qf90hvUhOl9gZJOgltrBNoeGuokHg8o+p60EyxDMa18QschCPhe48wYoSw==,iv:GYKzSn0FQ5I9em+CstsoQHshT0SNk+63J7CiPPisyjc=,tag:qaBpPabVysVQgZS/hY07ug==,type:str]
  telegram-chat-id: ENC[AES256_GCM,data:cowRYnut+h4gew==,iv:0fVnhGXpy2d4t8R/qStgyNi1WmLGt0tgo95dX7hB5jQ=,tag:WomvFTL2jfcOSuFwgPLfBw==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a1ZhKzFheDEvdnVwc3ZB
        cjQ0ejY1MWhrOGFpWHM0alZ1SitwUDdHTjNZClh2c0dXOFlJbE52c1VsRUpuU0M0
        V1N0NGYyK3VzSDdvUlNMWmtRTmkzN1kKLS0tIGZMU2lTd3JXelNyVmxITG5tZk5r
        OVY1T2xlUjkwR0x0QStjVEJ3czlQZzQKa5F3b4G2tvI8f83WbfN8bj25K1aXm1V0
        GXSMoOnLnWRMHz3jArEAb5Dw+7pxgHhJNvNuV6hFtfeIGa6OPodHFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T12:57:12Z"
  mac: ENC[AES256_GCM,data:r8yl5jVdKxtGHJzUFRhtTNJcNIjmEbW3rfL9Fgrn5jIPm+Dtdklh+95WWde/89ljKQC2zbSotokUApv2pGCzN7XnO+APVhh8folr+Io60wstUP2saGq2iHDdp8pMWCj07dVzKNQXXyRy3C2GZp2cteSknNosv0+cMuGgNspSFts=,iv:kEGCf66SLgqegw+yU+fWxdNaa5oFlPEuZVb0QGGrAKQ=,tag:96mRjNLML0Ihc0fTzdXFEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
