---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus-exemplars
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  prometheus-exemplars.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        isDefault: false
        editable: false
        overwrite: true
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: tempo
              urlDisplayLabel: "Voir dans Tempo"
