---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./alertmanager-secret.sops.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./ocirepository.yaml
  - ./grafana-dashboard-spring-boot.yaml
  - ./grafana-dashboard-homelab-nodes.yaml
  - ./grafana-dashboard-questify-red.yaml
  - ./grafana-dashboard-questify-business.yaml
  - ./grafana-dashboard-questify-errors.yaml
  - ./grafana-datasource-prometheus-exemplars.yaml
