apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-password: ENC[AES256_GCM,data:tAQEZmwtMR3Sa8M=,iv:X1srGHlIhjvX/gaCFdVWqbClX66MV8wnsj9jMpuJJCE=,tag:ROxPhJgqJfvkDsJVZldHog==,type:str]
  admin-user: ENC[AES256_GCM,data:xxaIHxU=,iv:ofFy1zL5i8WSprnaGGMzjMD6KzRVgTsBDLOVSoqFPkY=,tag:sWZdh0Yd1orGRQEZpucMQg==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOFNUMk8rNFBMeVFPZ3pt
        aytEcWlwRWlhUVA0b25tdDhUSjZ2OElualVRCnJMT2lBUlFsRHNOZStmc2pONVBK
        TEg4bjRzaXVPaXVCMGx1WkdTTXFqNzAKLS0tIEVNZlZQdzk1VncxUGVqUExxZUdu
        L1R2RzZLSGU1NGhHSWxUaU5OSDFUdG8Kps7cG8Wfs+Kpyt56sDjbE0yM88A3GQ6w
        czAIrOEkCsklQAlBO5wat6TnPPnnCBPJfLW6KwLK5cyMGUqpCWq1vA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T20:52:25Z"
  mac: ENC[AES256_GCM,data:5sQgWC6QcnNwnHhF2FshMhMqLULbLfMNgGpzFuaTrx0g4C9WVgFpU3DNEgr9PnPSKcceGRJ3JKPccR/oIRIiz0FVB6aYA6l4d0g8LVwGVqq5JJuMCQ8iXb459JyuwbpUhWi/kJ8DpdXDtPicatBhlTTE6IKxgHQGT4xtCpr3guU=,iv:pCDs9MTnmVnE+QaCAKdFCdGphFKxYXx017zMeXyfd8U=,tag:yESu5oaqRUOp+yF0TJeSkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
