---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: squirrel-backend
spec:
  image: ghcr.io/axelfrache/squirrel-backend
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: squirrel-frontend
spec:
  image: ghcr.io/axelfrache/squirrel-frontend
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: squirrel-backend
spec:
  imageRepositoryRef:
    name: squirrel-backend
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: squirrel-frontend
spec:
  imageRepositoryRef:
    name: squirrel-frontend
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: squirrel
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        name: refs/heads/main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: "chore(squirrel): update image digests"
    push:
      branch: main
  update:
    path: ./kubernetes/apps/squirrel
    strategy: Setters
