apiVersion: v1
kind: Secret
metadata:
  name: ghost-secret
stringData:
  DB_ROOT_PASSWORD: ENC[AES256_GCM,data:1fuheN1XSjOmbdPztLp5gCgZHnE85i6XxdgsYmLERluEfUMnej5+NkHjJO9buvj2,iv:0oRfVIwEFOtXVQpZOd7W4yFS9lUUe7lwST6nXi+xYaQ=,tag:tMd1SyDmHKS2Jf1LqhkXmA==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:yspYH6GNTFBLI3rmhY/w54892it3yCAZEzvNWqZecSH4y9WGPhlhQARoWOeWAqcl,iv:xzsnzzo79iHgzCKMe73SrEg0jR1zJFQXATalO9gpjVw=,tag:OiFGUdRbSobUv9QQDZpjow==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRjU2cnZtbHR4eTZrcjg3
        amJYZVNEa0krUHFObjVaMUYrdmtCcUdNTEZRCmY2cmlmaktlZlc3NFR3ajhoekFI
        OStjUkw5aUUxS0x1d3U0T3ZtaThoOVUKLS0tIGV4djFQYm8rVzVmUTA1VWxRempF
        eGY0ZUxJUkNYOEhSZS93a1RLK2doNTQKZs2lV/K1jsnjA2+g/F5h/1P3GyBeIoj3
        Kc9PCdGmdaJpVA7kYjbosEKzmiTfUjr4bsQV9YjkMoi8oH4DNn/zSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-20T08:14:59Z"
  mac: ENC[AES256_GCM,data:uQ+hUIpl4j/+Iviz9MOG8Ju8mDhXyokAj49DshdxpMvbtWYur9vP85EMolMtLrETj0yTT+xGbzPrzd/hMI1mIGCC7Ec7m00JYeqxIcaOJQIgCJP4Kez1UC+ZLmDHMMqrDL7VrrChTCKIU5thdHZzBTR8yqSYWaUA63CEfbKm/uc=,iv:EFMZYKEoQBB3X+vzSJ8LkQBgUou6whD4EUxMVolXSLQ=,tag:U2g8t0C8HPvfzjfSZwuTgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
