---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: questify-landing
spec:
  chartRef:
    kind: OCIRepository
    name: questify-landing
  interval: 1h
  values:
    controllers:
      questify-landing:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/axelfrache/questify-landing
              tag: latest
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 6
              readiness: *probes
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
              limits:
                memory: 128Mi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["getquestify.com"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
