---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  chartRef:
    kind: OCIRepository
    name: longhorn
  interval: 1h
  values:
    global:
      tolerations:
        - key: gpu
          operator: Equal
          value: "true"
          effect: NoSchedule
    defaultSettings:
      defaultReplicaCount: 2
      taintToleration: "gpu=true:NoSchedule"
      storageMinimalAvailablePercentage: 10
      storageReservedPercentageForDefaultDisk: 10
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
    longhornUI:
      replicas: 1
