apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_BASIC_AUTH_ACTIVE: ENC[AES256_GCM,data:ow08CA==,iv:xaA+YECAVHNtwkh8J8+Ukg7cfy3UMwmYNRZsQGOjO7A=,tag:zIcW1aFr+DwTLBdgwxP+xw==,type:str]
  N8N_BASIC_AUTH_USER: ENC[AES256_GCM,data:SuZnTWA=,iv:vThC8IEcbqZ5s4d2WJ6ZTS1xU0P1Uq5hENiiyEs3JVw=,tag:4DvXL81pCyFhsPMr/FuFAA==,type:str]
  N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:AIpAgdtkSakE+0M3lSntTNZJaRqBL1G5F0o08VBAvrg=,iv:X1rm6NXbXhCn+IFFrbI2MDQ/9be4pzIzd2RI8et8tRU=,tag:jhI5rBbovwqfYsWpt8F52A==,type:str]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:Xjt2SjxQr+2EhYqfhMuA5vCLSm5YGAyCFcwQIZ2tNYK170E8sHhp20+qUik1RxBa,iv:w9hI63sg3HAwEmK9ixtc+FnuQaIrlMdqXU15fn4mWJk=,tag:99i3dKpHubiUtVrZEon2vw==,type:str]
sops:
  age:
    - recipient: age1j6e3ff57dhwlfv60km0l3ehmrzldvtxkwmpeh3qev06wmenyldaqfpucld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eEd3aW5BRFV3QksvaFQy
        UllCVThDcG5RT3p6czZlWk9HSlZOdkVIMURzCmdFMUFmNXNwVHZuRlRSSzBZOEVi
        cytqR0RCY29lcG9lVk1BUzBmNis4ZTgKLS0tIFFUZXNHa0hKVk4wMy9Xdmx3Mi9Q
        dHNpd0JlcENXeENiQjdiWHpVT2tnWFUK1kWaF96MX1JnoWGlxmdjoLkW2yQUVP5L
        UU5cR+7K0k1npIJ4lWqdguNojYBMdUz+w5fXRaCR7vy4cV21xchqGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T18:03:06Z"
  mac: ENC[AES256_GCM,data:P4hSGkRafp9gDxv2gULo13oVkwoifaeWXhRmieMciZBKASfhKX5kpvIagxQuUwa7QWXzQUl8jPYoq2j8IJDdYlfq2SvwYb+8Lg2yNEMeJBZfFDZJhT2jPho9D4Lll5O2Jnhj9MC183lz5nOvt/Srh7PAX2HSWNCoPFapE3/q8uk=,iv:iRPt0Hyj5GFXfUioFK3mtoeLlzAFGP5kotOirsEkyHk=,tag:Go7yrLQ9q47DYyiCjCD3yA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
