---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  namespace: kube-system
  labels:
    app: intel-gpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-gpu-plugin
  template:
    metadata:
      labels:
        app: intel-gpu-plugin
    spec:
      nodeSelector:
        gpu: "true"
      tolerations:
        - key: gpu
          operator: Equal
          value: "true"
          effect: NoSchedule
      priorityClassName: system-node-critical
      containers:
        - name: intel-gpu-plugin
          image: intel/intel-gpu-plugin:0.32.1
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
          args:
            - -shared-dev-num=2
          volumeMounts:
            - name: devfs
              mountPath: /dev/dri
              readOnly: true
            - name: sysfs
              mountPath: /sys/class/drm
              readOnly: true
            - name: kubeletsockets
              mountPath: /var/lib/kubelet/device-plugins
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
      volumes:
        - name: devfs
          hostPath:
            path: /dev/dri
        - name: sysfs
          hostPath:
            path: /sys/class/drm
        - name: kubeletsockets
          hostPath:
            path: /var/lib/kubelet/device-plugins
