---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./cnpg
  - ./default
  - ./flux-system
  - ./ghost
  - ./gitea
  - ./iot
  - ./keel
  - ./kube-system
  - ./latex
  - ./media
  - ./monitoring
  - ./n8n
  - ./network
  - ./openproject
  - ./plantuml
  - ./questify
  - ./security
  - ./squirrel
  - ./storage
