---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adventurelog

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./adventurelog-db/ks.yaml
  - ./adventurelog-app/ks.yaml
